### ISSUE TITLE
A question about 'load_clip_to_cpu' function

### ISSUE THREAD

**Issue by baek85** [muzairkhattak/PromptSRC#1]
Thank you for sharing your great work.

There are 2 lines from the function 'load_clip_to_cpu' that exists in every file in trainer folder.

model_path = clip._download(url)  
model = clip.build_model(state_dict or model.state_dict(), design_details)

In my environment, clip._download function needs 'model_backbone_path' and clip.build_model function takes 1 positional argument.

Is there a library version issue or something?

How can i handle these issues?

**Comment by muzairkhattak** [comment]
Hi  @baek85,

Thank you for showing interest in PromptSRC!

Regarding your query, kindly note that we have made changes in the original CLIP code, which is why your are seeing additional positional arguments in the CLIP functions. 

We have redefined the CLIP function definitions within our PromptSRC repo, so these function calls will automatically use the modified function definitions. For example,  clip.build_model is redefined [here in our repo.](https://github.com/muzairkhattak/PromptSRC/blob/5db4687161d06ce26b536a010bcdcc9dd569e5f5/clip/model.py#L656)

Please let us know if you have any additional question.

Thank you and kind regards!

**Comment by baek85** [comment]
It's my probelm in combine this code with others.

Thank you for quick answering!
