### ISSUE TITLE
RuntimeError: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by JiangjiangLan** [muzairkhattak/PromptSRC#6]
Hello, @muzairkhattak 
    I encountered the following issue during operation: **RuntimeError: grad can be implicitly created only for scalar outputs**，may what the reason is?

**Comment by muzairkhattak** [comment]
Hi @JiangjiangLan, 

I think this is because you are using multiple GPUs to run our code, while our code currently support single-GPU training. 

To train your models on single GPU, please use `CUDA_VISIBLE_DEVICES=0` before the command that you are running on terminal.

I hope that would be helpful!

Thank you and kind regards!
